require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BillPreparesController do

  # This should return the minimal set of attributes required to create a valid
  # BillPrepare. As you add validations to BillPrepare, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all bill_prepares as @bill_prepares" do
      bill_prepare = BillPrepare.create! valid_attributes
      get :index
      assigns(:bill_prepares).should eq([bill_prepare])
    end
  end

  describe "GET show" do
    it "assigns the requested bill_prepare as @bill_prepare" do
      bill_prepare = BillPrepare.create! valid_attributes
      get :show, :id => bill_prepare.id
      assigns(:bill_prepare).should eq(bill_prepare)
    end
  end

  describe "GET new" do
    it "assigns a new bill_prepare as @bill_prepare" do
      get :new
      assigns(:bill_prepare).should be_a_new(BillPrepare)
    end
  end

  describe "GET edit" do
    it "assigns the requested bill_prepare as @bill_prepare" do
      bill_prepare = BillPrepare.create! valid_attributes
      get :edit, :id => bill_prepare.id
      assigns(:bill_prepare).should eq(bill_prepare)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BillPrepare" do
        expect {
          post :create, :bill_prepare => valid_attributes
        }.to change(BillPrepare, :count).by(1)
      end

      it "assigns a newly created bill_prepare as @bill_prepare" do
        post :create, :bill_prepare => valid_attributes
        assigns(:bill_prepare).should be_a(BillPrepare)
        assigns(:bill_prepare).should be_persisted
      end

      it "redirects to the created bill_prepare" do
        post :create, :bill_prepare => valid_attributes
        response.should redirect_to(BillPrepare.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bill_prepare as @bill_prepare" do
        # Trigger the behavior that occurs when invalid params are submitted
        BillPrepare.any_instance.stub(:save).and_return(false)
        post :create, :bill_prepare => {}
        assigns(:bill_prepare).should be_a_new(BillPrepare)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BillPrepare.any_instance.stub(:save).and_return(false)
        post :create, :bill_prepare => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bill_prepare" do
        bill_prepare = BillPrepare.create! valid_attributes
        # Assuming there are no other bill_prepares in the database, this
        # specifies that the BillPrepare created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BillPrepare.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => bill_prepare.id, :bill_prepare => {'these' => 'params'}
      end

      it "assigns the requested bill_prepare as @bill_prepare" do
        bill_prepare = BillPrepare.create! valid_attributes
        put :update, :id => bill_prepare.id, :bill_prepare => valid_attributes
        assigns(:bill_prepare).should eq(bill_prepare)
      end

      it "redirects to the bill_prepare" do
        bill_prepare = BillPrepare.create! valid_attributes
        put :update, :id => bill_prepare.id, :bill_prepare => valid_attributes
        response.should redirect_to(bill_prepare)
      end
    end

    describe "with invalid params" do
      it "assigns the bill_prepare as @bill_prepare" do
        bill_prepare = BillPrepare.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BillPrepare.any_instance.stub(:save).and_return(false)
        put :update, :id => bill_prepare.id, :bill_prepare => {}
        assigns(:bill_prepare).should eq(bill_prepare)
      end

      it "re-renders the 'edit' template" do
        bill_prepare = BillPrepare.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BillPrepare.any_instance.stub(:save).and_return(false)
        put :update, :id => bill_prepare.id, :bill_prepare => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bill_prepare" do
      bill_prepare = BillPrepare.create! valid_attributes
      expect {
        delete :destroy, :id => bill_prepare.id
      }.to change(BillPrepare, :count).by(-1)
    end

    it "redirects to the bill_prepares list" do
      bill_prepare = BillPrepare.create! valid_attributes
      delete :destroy, :id => bill_prepare.id
      response.should redirect_to(bill_prepares_url)
    end
  end

end
