require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BusiCommunicationsController do

  # This should return the minimal set of attributes required to create a valid
  # BusiCommunication. As you add validations to BusiCommunication, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all busi_communications as @busi_communications" do
      busi_communication = BusiCommunication.create! valid_attributes
      get :index
      assigns(:busi_communications).should eq([busi_communication])
    end
  end

  describe "GET show" do
    it "assigns the requested busi_communication as @busi_communication" do
      busi_communication = BusiCommunication.create! valid_attributes
      get :show, :id => busi_communication.id
      assigns(:busi_communication).should eq(busi_communication)
    end
  end

  describe "GET new" do
    it "assigns a new busi_communication as @busi_communication" do
      get :new
      assigns(:busi_communication).should be_a_new(BusiCommunication)
    end
  end

  describe "GET edit" do
    it "assigns the requested busi_communication as @busi_communication" do
      busi_communication = BusiCommunication.create! valid_attributes
      get :edit, :id => busi_communication.id
      assigns(:busi_communication).should eq(busi_communication)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BusiCommunication" do
        expect {
          post :create, :busi_communication => valid_attributes
        }.to change(BusiCommunication, :count).by(1)
      end

      it "assigns a newly created busi_communication as @busi_communication" do
        post :create, :busi_communication => valid_attributes
        assigns(:busi_communication).should be_a(BusiCommunication)
        assigns(:busi_communication).should be_persisted
      end

      it "redirects to the created busi_communication" do
        post :create, :busi_communication => valid_attributes
        response.should redirect_to(BusiCommunication.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved busi_communication as @busi_communication" do
        # Trigger the behavior that occurs when invalid params are submitted
        BusiCommunication.any_instance.stub(:save).and_return(false)
        post :create, :busi_communication => {}
        assigns(:busi_communication).should be_a_new(BusiCommunication)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BusiCommunication.any_instance.stub(:save).and_return(false)
        post :create, :busi_communication => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested busi_communication" do
        busi_communication = BusiCommunication.create! valid_attributes
        # Assuming there are no other busi_communications in the database, this
        # specifies that the BusiCommunication created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BusiCommunication.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => busi_communication.id, :busi_communication => {'these' => 'params'}
      end

      it "assigns the requested busi_communication as @busi_communication" do
        busi_communication = BusiCommunication.create! valid_attributes
        put :update, :id => busi_communication.id, :busi_communication => valid_attributes
        assigns(:busi_communication).should eq(busi_communication)
      end

      it "redirects to the busi_communication" do
        busi_communication = BusiCommunication.create! valid_attributes
        put :update, :id => busi_communication.id, :busi_communication => valid_attributes
        response.should redirect_to(busi_communication)
      end
    end

    describe "with invalid params" do
      it "assigns the busi_communication as @busi_communication" do
        busi_communication = BusiCommunication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BusiCommunication.any_instance.stub(:save).and_return(false)
        put :update, :id => busi_communication.id, :busi_communication => {}
        assigns(:busi_communication).should eq(busi_communication)
      end

      it "re-renders the 'edit' template" do
        busi_communication = BusiCommunication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BusiCommunication.any_instance.stub(:save).and_return(false)
        put :update, :id => busi_communication.id, :busi_communication => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested busi_communication" do
      busi_communication = BusiCommunication.create! valid_attributes
      expect {
        delete :destroy, :id => busi_communication.id
      }.to change(BusiCommunication, :count).by(-1)
    end

    it "redirects to the busi_communications list" do
      busi_communication = BusiCommunication.create! valid_attributes
      delete :destroy, :id => busi_communication.id
      response.should redirect_to(busi_communications_url)
    end
  end

end
