require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BxyProjectsController do

  # This should return the minimal set of attributes required to create a valid
  # BxyProject. As you add validations to BxyProject, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all bxy_projects as @bxy_projects" do
      bxy_project = BxyProject.create! valid_attributes
      get :index
      assigns(:bxy_projects).should eq([bxy_project])
    end
  end

  describe "GET show" do
    it "assigns the requested bxy_project as @bxy_project" do
      bxy_project = BxyProject.create! valid_attributes
      get :show, :id => bxy_project.id
      assigns(:bxy_project).should eq(bxy_project)
    end
  end

  describe "GET new" do
    it "assigns a new bxy_project as @bxy_project" do
      get :new
      assigns(:bxy_project).should be_a_new(BxyProject)
    end
  end

  describe "GET edit" do
    it "assigns the requested bxy_project as @bxy_project" do
      bxy_project = BxyProject.create! valid_attributes
      get :edit, :id => bxy_project.id
      assigns(:bxy_project).should eq(bxy_project)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BxyProject" do
        expect {
          post :create, :bxy_project => valid_attributes
        }.to change(BxyProject, :count).by(1)
      end

      it "assigns a newly created bxy_project as @bxy_project" do
        post :create, :bxy_project => valid_attributes
        assigns(:bxy_project).should be_a(BxyProject)
        assigns(:bxy_project).should be_persisted
      end

      it "redirects to the created bxy_project" do
        post :create, :bxy_project => valid_attributes
        response.should redirect_to(BxyProject.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bxy_project as @bxy_project" do
        # Trigger the behavior that occurs when invalid params are submitted
        BxyProject.any_instance.stub(:save).and_return(false)
        post :create, :bxy_project => {}
        assigns(:bxy_project).should be_a_new(BxyProject)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BxyProject.any_instance.stub(:save).and_return(false)
        post :create, :bxy_project => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bxy_project" do
        bxy_project = BxyProject.create! valid_attributes
        # Assuming there are no other bxy_projects in the database, this
        # specifies that the BxyProject created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BxyProject.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => bxy_project.id, :bxy_project => {'these' => 'params'}
      end

      it "assigns the requested bxy_project as @bxy_project" do
        bxy_project = BxyProject.create! valid_attributes
        put :update, :id => bxy_project.id, :bxy_project => valid_attributes
        assigns(:bxy_project).should eq(bxy_project)
      end

      it "redirects to the bxy_project" do
        bxy_project = BxyProject.create! valid_attributes
        put :update, :id => bxy_project.id, :bxy_project => valid_attributes
        response.should redirect_to(bxy_project)
      end
    end

    describe "with invalid params" do
      it "assigns the bxy_project as @bxy_project" do
        bxy_project = BxyProject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BxyProject.any_instance.stub(:save).and_return(false)
        put :update, :id => bxy_project.id, :bxy_project => {}
        assigns(:bxy_project).should eq(bxy_project)
      end

      it "re-renders the 'edit' template" do
        bxy_project = BxyProject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BxyProject.any_instance.stub(:save).and_return(false)
        put :update, :id => bxy_project.id, :bxy_project => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bxy_project" do
      bxy_project = BxyProject.create! valid_attributes
      expect {
        delete :destroy, :id => bxy_project.id
      }.to change(BxyProject, :count).by(-1)
    end

    it "redirects to the bxy_projects list" do
      bxy_project = BxyProject.create! valid_attributes
      delete :destroy, :id => bxy_project.id
      response.should redirect_to(bxy_projects_url)
    end
  end

end
