require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CompetitorsController do

  # This should return the minimal set of attributes required to create a valid
  # Competitor. As you add validations to Competitor, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all competitors as @competitors" do
      competitor = Competitor.create! valid_attributes
      get :index
      assigns(:competitors).should eq([competitor])
    end
  end

  describe "GET show" do
    it "assigns the requested competitor as @competitor" do
      competitor = Competitor.create! valid_attributes
      get :show, :id => competitor.id
      assigns(:competitor).should eq(competitor)
    end
  end

  describe "GET new" do
    it "assigns a new competitor as @competitor" do
      get :new
      assigns(:competitor).should be_a_new(Competitor)
    end
  end

  describe "GET edit" do
    it "assigns the requested competitor as @competitor" do
      competitor = Competitor.create! valid_attributes
      get :edit, :id => competitor.id
      assigns(:competitor).should eq(competitor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Competitor" do
        expect {
          post :create, :competitor => valid_attributes
        }.to change(Competitor, :count).by(1)
      end

      it "assigns a newly created competitor as @competitor" do
        post :create, :competitor => valid_attributes
        assigns(:competitor).should be_a(Competitor)
        assigns(:competitor).should be_persisted
      end

      it "redirects to the created competitor" do
        post :create, :competitor => valid_attributes
        response.should redirect_to(Competitor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved competitor as @competitor" do
        # Trigger the behavior that occurs when invalid params are submitted
        Competitor.any_instance.stub(:save).and_return(false)
        post :create, :competitor => {}
        assigns(:competitor).should be_a_new(Competitor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Competitor.any_instance.stub(:save).and_return(false)
        post :create, :competitor => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested competitor" do
        competitor = Competitor.create! valid_attributes
        # Assuming there are no other competitors in the database, this
        # specifies that the Competitor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Competitor.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => competitor.id, :competitor => {'these' => 'params'}
      end

      it "assigns the requested competitor as @competitor" do
        competitor = Competitor.create! valid_attributes
        put :update, :id => competitor.id, :competitor => valid_attributes
        assigns(:competitor).should eq(competitor)
      end

      it "redirects to the competitor" do
        competitor = Competitor.create! valid_attributes
        put :update, :id => competitor.id, :competitor => valid_attributes
        response.should redirect_to(competitor)
      end
    end

    describe "with invalid params" do
      it "assigns the competitor as @competitor" do
        competitor = Competitor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Competitor.any_instance.stub(:save).and_return(false)
        put :update, :id => competitor.id, :competitor => {}
        assigns(:competitor).should eq(competitor)
      end

      it "re-renders the 'edit' template" do
        competitor = Competitor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Competitor.any_instance.stub(:save).and_return(false)
        put :update, :id => competitor.id, :competitor => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested competitor" do
      competitor = Competitor.create! valid_attributes
      expect {
        delete :destroy, :id => competitor.id
      }.to change(Competitor, :count).by(-1)
    end

    it "redirects to the competitors list" do
      competitor = Competitor.create! valid_attributes
      delete :destroy, :id => competitor.id
      response.should redirect_to(competitors_url)
    end
  end

end
