require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CustomerContactsController do

  # This should return the minimal set of attributes required to create a valid
  # CustomerContact. As you add validations to CustomerContact, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all customer_contacts as @customer_contacts" do
      customer_contact = CustomerContact.create! valid_attributes
      get :index
      assigns(:customer_contacts).should eq([customer_contact])
    end
  end

  describe "GET show" do
    it "assigns the requested customer_contact as @customer_contact" do
      customer_contact = CustomerContact.create! valid_attributes
      get :show, :id => customer_contact.id
      assigns(:customer_contact).should eq(customer_contact)
    end
  end

  describe "GET new" do
    it "assigns a new customer_contact as @customer_contact" do
      get :new
      assigns(:customer_contact).should be_a_new(CustomerContact)
    end
  end

  describe "GET edit" do
    it "assigns the requested customer_contact as @customer_contact" do
      customer_contact = CustomerContact.create! valid_attributes
      get :edit, :id => customer_contact.id
      assigns(:customer_contact).should eq(customer_contact)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CustomerContact" do
        expect {
          post :create, :customer_contact => valid_attributes
        }.to change(CustomerContact, :count).by(1)
      end

      it "assigns a newly created customer_contact as @customer_contact" do
        post :create, :customer_contact => valid_attributes
        assigns(:customer_contact).should be_a(CustomerContact)
        assigns(:customer_contact).should be_persisted
      end

      it "redirects to the created customer_contact" do
        post :create, :customer_contact => valid_attributes
        response.should redirect_to(CustomerContact.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved customer_contact as @customer_contact" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerContact.any_instance.stub(:save).and_return(false)
        post :create, :customer_contact => {}
        assigns(:customer_contact).should be_a_new(CustomerContact)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerContact.any_instance.stub(:save).and_return(false)
        post :create, :customer_contact => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested customer_contact" do
        customer_contact = CustomerContact.create! valid_attributes
        # Assuming there are no other customer_contacts in the database, this
        # specifies that the CustomerContact created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CustomerContact.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => customer_contact.id, :customer_contact => {'these' => 'params'}
      end

      it "assigns the requested customer_contact as @customer_contact" do
        customer_contact = CustomerContact.create! valid_attributes
        put :update, :id => customer_contact.id, :customer_contact => valid_attributes
        assigns(:customer_contact).should eq(customer_contact)
      end

      it "redirects to the customer_contact" do
        customer_contact = CustomerContact.create! valid_attributes
        put :update, :id => customer_contact.id, :customer_contact => valid_attributes
        response.should redirect_to(customer_contact)
      end
    end

    describe "with invalid params" do
      it "assigns the customer_contact as @customer_contact" do
        customer_contact = CustomerContact.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerContact.any_instance.stub(:save).and_return(false)
        put :update, :id => customer_contact.id, :customer_contact => {}
        assigns(:customer_contact).should eq(customer_contact)
      end

      it "re-renders the 'edit' template" do
        customer_contact = CustomerContact.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerContact.any_instance.stub(:save).and_return(false)
        put :update, :id => customer_contact.id, :customer_contact => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested customer_contact" do
      customer_contact = CustomerContact.create! valid_attributes
      expect {
        delete :destroy, :id => customer_contact.id
      }.to change(CustomerContact, :count).by(-1)
    end

    it "redirects to the customer_contacts list" do
      customer_contact = CustomerContact.create! valid_attributes
      delete :destroy, :id => customer_contact.id
      response.should redirect_to(customer_contacts_url)
    end
  end

end
