require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DocAmountChangesController do

  # This should return the minimal set of attributes required to create a valid
  # DocAmountChange. As you add validations to DocAmountChange, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all doc_amount_changes as @doc_amount_changes" do
      doc_amount_change = DocAmountChange.create! valid_attributes
      get :index
      assigns(:doc_amount_changes).should eq([doc_amount_change])
    end
  end

  describe "GET show" do
    it "assigns the requested doc_amount_change as @doc_amount_change" do
      doc_amount_change = DocAmountChange.create! valid_attributes
      get :show, :id => doc_amount_change.id
      assigns(:doc_amount_change).should eq(doc_amount_change)
    end
  end

  describe "GET new" do
    it "assigns a new doc_amount_change as @doc_amount_change" do
      get :new
      assigns(:doc_amount_change).should be_a_new(DocAmountChange)
    end
  end

  describe "GET edit" do
    it "assigns the requested doc_amount_change as @doc_amount_change" do
      doc_amount_change = DocAmountChange.create! valid_attributes
      get :edit, :id => doc_amount_change.id
      assigns(:doc_amount_change).should eq(doc_amount_change)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DocAmountChange" do
        expect {
          post :create, :doc_amount_change => valid_attributes
        }.to change(DocAmountChange, :count).by(1)
      end

      it "assigns a newly created doc_amount_change as @doc_amount_change" do
        post :create, :doc_amount_change => valid_attributes
        assigns(:doc_amount_change).should be_a(DocAmountChange)
        assigns(:doc_amount_change).should be_persisted
      end

      it "redirects to the created doc_amount_change" do
        post :create, :doc_amount_change => valid_attributes
        response.should redirect_to(DocAmountChange.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved doc_amount_change as @doc_amount_change" do
        # Trigger the behavior that occurs when invalid params are submitted
        DocAmountChange.any_instance.stub(:save).and_return(false)
        post :create, :doc_amount_change => {}
        assigns(:doc_amount_change).should be_a_new(DocAmountChange)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DocAmountChange.any_instance.stub(:save).and_return(false)
        post :create, :doc_amount_change => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested doc_amount_change" do
        doc_amount_change = DocAmountChange.create! valid_attributes
        # Assuming there are no other doc_amount_changes in the database, this
        # specifies that the DocAmountChange created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DocAmountChange.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => doc_amount_change.id, :doc_amount_change => {'these' => 'params'}
      end

      it "assigns the requested doc_amount_change as @doc_amount_change" do
        doc_amount_change = DocAmountChange.create! valid_attributes
        put :update, :id => doc_amount_change.id, :doc_amount_change => valid_attributes
        assigns(:doc_amount_change).should eq(doc_amount_change)
      end

      it "redirects to the doc_amount_change" do
        doc_amount_change = DocAmountChange.create! valid_attributes
        put :update, :id => doc_amount_change.id, :doc_amount_change => valid_attributes
        response.should redirect_to(doc_amount_change)
      end
    end

    describe "with invalid params" do
      it "assigns the doc_amount_change as @doc_amount_change" do
        doc_amount_change = DocAmountChange.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DocAmountChange.any_instance.stub(:save).and_return(false)
        put :update, :id => doc_amount_change.id, :doc_amount_change => {}
        assigns(:doc_amount_change).should eq(doc_amount_change)
      end

      it "re-renders the 'edit' template" do
        doc_amount_change = DocAmountChange.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DocAmountChange.any_instance.stub(:save).and_return(false)
        put :update, :id => doc_amount_change.id, :doc_amount_change => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested doc_amount_change" do
      doc_amount_change = DocAmountChange.create! valid_attributes
      expect {
        delete :destroy, :id => doc_amount_change.id
      }.to change(DocAmountChange, :count).by(-1)
    end

    it "redirects to the doc_amount_changes list" do
      doc_amount_change = DocAmountChange.create! valid_attributes
      delete :destroy, :id => doc_amount_change.id
      response.should redirect_to(doc_amount_changes_url)
    end
  end

end
