require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ImplementActivitiesController do

  # This should return the minimal set of attributes required to create a valid
  # ImplementActivity. As you add validations to ImplementActivity, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all implement_activities as @implement_activities" do
      implement_activity = ImplementActivity.create! valid_attributes
      get :index
      assigns(:implement_activities).should eq([implement_activity])
    end
  end

  describe "GET show" do
    it "assigns the requested implement_activity as @implement_activity" do
      implement_activity = ImplementActivity.create! valid_attributes
      get :show, :id => implement_activity.id
      assigns(:implement_activity).should eq(implement_activity)
    end
  end

  describe "GET new" do
    it "assigns a new implement_activity as @implement_activity" do
      get :new
      assigns(:implement_activity).should be_a_new(ImplementActivity)
    end
  end

  describe "GET edit" do
    it "assigns the requested implement_activity as @implement_activity" do
      implement_activity = ImplementActivity.create! valid_attributes
      get :edit, :id => implement_activity.id
      assigns(:implement_activity).should eq(implement_activity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ImplementActivity" do
        expect {
          post :create, :implement_activity => valid_attributes
        }.to change(ImplementActivity, :count).by(1)
      end

      it "assigns a newly created implement_activity as @implement_activity" do
        post :create, :implement_activity => valid_attributes
        assigns(:implement_activity).should be_a(ImplementActivity)
        assigns(:implement_activity).should be_persisted
      end

      it "redirects to the created implement_activity" do
        post :create, :implement_activity => valid_attributes
        response.should redirect_to(ImplementActivity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved implement_activity as @implement_activity" do
        # Trigger the behavior that occurs when invalid params are submitted
        ImplementActivity.any_instance.stub(:save).and_return(false)
        post :create, :implement_activity => {}
        assigns(:implement_activity).should be_a_new(ImplementActivity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ImplementActivity.any_instance.stub(:save).and_return(false)
        post :create, :implement_activity => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested implement_activity" do
        implement_activity = ImplementActivity.create! valid_attributes
        # Assuming there are no other implement_activities in the database, this
        # specifies that the ImplementActivity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ImplementActivity.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => implement_activity.id, :implement_activity => {'these' => 'params'}
      end

      it "assigns the requested implement_activity as @implement_activity" do
        implement_activity = ImplementActivity.create! valid_attributes
        put :update, :id => implement_activity.id, :implement_activity => valid_attributes
        assigns(:implement_activity).should eq(implement_activity)
      end

      it "redirects to the implement_activity" do
        implement_activity = ImplementActivity.create! valid_attributes
        put :update, :id => implement_activity.id, :implement_activity => valid_attributes
        response.should redirect_to(implement_activity)
      end
    end

    describe "with invalid params" do
      it "assigns the implement_activity as @implement_activity" do
        implement_activity = ImplementActivity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ImplementActivity.any_instance.stub(:save).and_return(false)
        put :update, :id => implement_activity.id, :implement_activity => {}
        assigns(:implement_activity).should eq(implement_activity)
      end

      it "re-renders the 'edit' template" do
        implement_activity = ImplementActivity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ImplementActivity.any_instance.stub(:save).and_return(false)
        put :update, :id => implement_activity.id, :implement_activity => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested implement_activity" do
      implement_activity = ImplementActivity.create! valid_attributes
      expect {
        delete :destroy, :id => implement_activity.id
      }.to change(ImplementActivity, :count).by(-1)
    end

    it "redirects to the implement_activities list" do
      implement_activity = ImplementActivity.create! valid_attributes
      delete :destroy, :id => implement_activity.id
      response.should redirect_to(implement_activities_url)
    end
  end

end
