require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NetworkConditionsController do

  # This should return the minimal set of attributes required to create a valid
  # NetworkCondition. As you add validations to NetworkCondition, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all network_conditions as @network_conditions" do
      network_condition = NetworkCondition.create! valid_attributes
      get :index
      assigns(:network_conditions).should eq([network_condition])
    end
  end

  describe "GET show" do
    it "assigns the requested network_condition as @network_condition" do
      network_condition = NetworkCondition.create! valid_attributes
      get :show, :id => network_condition.id
      assigns(:network_condition).should eq(network_condition)
    end
  end

  describe "GET new" do
    it "assigns a new network_condition as @network_condition" do
      get :new
      assigns(:network_condition).should be_a_new(NetworkCondition)
    end
  end

  describe "GET edit" do
    it "assigns the requested network_condition as @network_condition" do
      network_condition = NetworkCondition.create! valid_attributes
      get :edit, :id => network_condition.id
      assigns(:network_condition).should eq(network_condition)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NetworkCondition" do
        expect {
          post :create, :network_condition => valid_attributes
        }.to change(NetworkCondition, :count).by(1)
      end

      it "assigns a newly created network_condition as @network_condition" do
        post :create, :network_condition => valid_attributes
        assigns(:network_condition).should be_a(NetworkCondition)
        assigns(:network_condition).should be_persisted
      end

      it "redirects to the created network_condition" do
        post :create, :network_condition => valid_attributes
        response.should redirect_to(NetworkCondition.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved network_condition as @network_condition" do
        # Trigger the behavior that occurs when invalid params are submitted
        NetworkCondition.any_instance.stub(:save).and_return(false)
        post :create, :network_condition => {}
        assigns(:network_condition).should be_a_new(NetworkCondition)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NetworkCondition.any_instance.stub(:save).and_return(false)
        post :create, :network_condition => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested network_condition" do
        network_condition = NetworkCondition.create! valid_attributes
        # Assuming there are no other network_conditions in the database, this
        # specifies that the NetworkCondition created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NetworkCondition.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => network_condition.id, :network_condition => {'these' => 'params'}
      end

      it "assigns the requested network_condition as @network_condition" do
        network_condition = NetworkCondition.create! valid_attributes
        put :update, :id => network_condition.id, :network_condition => valid_attributes
        assigns(:network_condition).should eq(network_condition)
      end

      it "redirects to the network_condition" do
        network_condition = NetworkCondition.create! valid_attributes
        put :update, :id => network_condition.id, :network_condition => valid_attributes
        response.should redirect_to(network_condition)
      end
    end

    describe "with invalid params" do
      it "assigns the network_condition as @network_condition" do
        network_condition = NetworkCondition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NetworkCondition.any_instance.stub(:save).and_return(false)
        put :update, :id => network_condition.id, :network_condition => {}
        assigns(:network_condition).should eq(network_condition)
      end

      it "re-renders the 'edit' template" do
        network_condition = NetworkCondition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NetworkCondition.any_instance.stub(:save).and_return(false)
        put :update, :id => network_condition.id, :network_condition => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested network_condition" do
      network_condition = NetworkCondition.create! valid_attributes
      expect {
        delete :destroy, :id => network_condition.id
      }.to change(NetworkCondition, :count).by(-1)
    end

    it "redirects to the network_conditions list" do
      network_condition = NetworkCondition.create! valid_attributes
      delete :destroy, :id => network_condition.id
      response.should redirect_to(network_conditions_url)
    end
  end

end
