require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProductTestsController do

  # This should return the minimal set of attributes required to create a valid
  # ProductTest. As you add validations to ProductTest, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all product_tests as @product_tests" do
      product_test = ProductTest.create! valid_attributes
      get :index
      assigns(:product_tests).should eq([product_test])
    end
  end

  describe "GET show" do
    it "assigns the requested product_test as @product_test" do
      product_test = ProductTest.create! valid_attributes
      get :show, :id => product_test.id
      assigns(:product_test).should eq(product_test)
    end
  end

  describe "GET new" do
    it "assigns a new product_test as @product_test" do
      get :new
      assigns(:product_test).should be_a_new(ProductTest)
    end
  end

  describe "GET edit" do
    it "assigns the requested product_test as @product_test" do
      product_test = ProductTest.create! valid_attributes
      get :edit, :id => product_test.id
      assigns(:product_test).should eq(product_test)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProductTest" do
        expect {
          post :create, :product_test => valid_attributes
        }.to change(ProductTest, :count).by(1)
      end

      it "assigns a newly created product_test as @product_test" do
        post :create, :product_test => valid_attributes
        assigns(:product_test).should be_a(ProductTest)
        assigns(:product_test).should be_persisted
      end

      it "redirects to the created product_test" do
        post :create, :product_test => valid_attributes
        response.should redirect_to(ProductTest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved product_test as @product_test" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductTest.any_instance.stub(:save).and_return(false)
        post :create, :product_test => {}
        assigns(:product_test).should be_a_new(ProductTest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductTest.any_instance.stub(:save).and_return(false)
        post :create, :product_test => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested product_test" do
        product_test = ProductTest.create! valid_attributes
        # Assuming there are no other product_tests in the database, this
        # specifies that the ProductTest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProductTest.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => product_test.id, :product_test => {'these' => 'params'}
      end

      it "assigns the requested product_test as @product_test" do
        product_test = ProductTest.create! valid_attributes
        put :update, :id => product_test.id, :product_test => valid_attributes
        assigns(:product_test).should eq(product_test)
      end

      it "redirects to the product_test" do
        product_test = ProductTest.create! valid_attributes
        put :update, :id => product_test.id, :product_test => valid_attributes
        response.should redirect_to(product_test)
      end
    end

    describe "with invalid params" do
      it "assigns the product_test as @product_test" do
        product_test = ProductTest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductTest.any_instance.stub(:save).and_return(false)
        put :update, :id => product_test.id, :product_test => {}
        assigns(:product_test).should eq(product_test)
      end

      it "re-renders the 'edit' template" do
        product_test = ProductTest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductTest.any_instance.stub(:save).and_return(false)
        put :update, :id => product_test.id, :product_test => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested product_test" do
      product_test = ProductTest.create! valid_attributes
      expect {
        delete :destroy, :id => product_test.id
      }.to change(ProductTest, :count).by(-1)
    end

    it "redirects to the product_tests list" do
      product_test = ProductTest.create! valid_attributes
      delete :destroy, :id => product_test.id
      response.should redirect_to(product_tests_url)
    end
  end

end
