require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TechCommunicationsController do

  # This should return the minimal set of attributes required to create a valid
  # TechCommunication. As you add validations to TechCommunication, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all tech_communications as @tech_communications" do
      tech_communication = TechCommunication.create! valid_attributes
      get :index
      assigns(:tech_communications).should eq([tech_communication])
    end
  end

  describe "GET show" do
    it "assigns the requested tech_communication as @tech_communication" do
      tech_communication = TechCommunication.create! valid_attributes
      get :show, :id => tech_communication.id
      assigns(:tech_communication).should eq(tech_communication)
    end
  end

  describe "GET new" do
    it "assigns a new tech_communication as @tech_communication" do
      get :new
      assigns(:tech_communication).should be_a_new(TechCommunication)
    end
  end

  describe "GET edit" do
    it "assigns the requested tech_communication as @tech_communication" do
      tech_communication = TechCommunication.create! valid_attributes
      get :edit, :id => tech_communication.id
      assigns(:tech_communication).should eq(tech_communication)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TechCommunication" do
        expect {
          post :create, :tech_communication => valid_attributes
        }.to change(TechCommunication, :count).by(1)
      end

      it "assigns a newly created tech_communication as @tech_communication" do
        post :create, :tech_communication => valid_attributes
        assigns(:tech_communication).should be_a(TechCommunication)
        assigns(:tech_communication).should be_persisted
      end

      it "redirects to the created tech_communication" do
        post :create, :tech_communication => valid_attributes
        response.should redirect_to(TechCommunication.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tech_communication as @tech_communication" do
        # Trigger the behavior that occurs when invalid params are submitted
        TechCommunication.any_instance.stub(:save).and_return(false)
        post :create, :tech_communication => {}
        assigns(:tech_communication).should be_a_new(TechCommunication)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TechCommunication.any_instance.stub(:save).and_return(false)
        post :create, :tech_communication => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tech_communication" do
        tech_communication = TechCommunication.create! valid_attributes
        # Assuming there are no other tech_communications in the database, this
        # specifies that the TechCommunication created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TechCommunication.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => tech_communication.id, :tech_communication => {'these' => 'params'}
      end

      it "assigns the requested tech_communication as @tech_communication" do
        tech_communication = TechCommunication.create! valid_attributes
        put :update, :id => tech_communication.id, :tech_communication => valid_attributes
        assigns(:tech_communication).should eq(tech_communication)
      end

      it "redirects to the tech_communication" do
        tech_communication = TechCommunication.create! valid_attributes
        put :update, :id => tech_communication.id, :tech_communication => valid_attributes
        response.should redirect_to(tech_communication)
      end
    end

    describe "with invalid params" do
      it "assigns the tech_communication as @tech_communication" do
        tech_communication = TechCommunication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TechCommunication.any_instance.stub(:save).and_return(false)
        put :update, :id => tech_communication.id, :tech_communication => {}
        assigns(:tech_communication).should eq(tech_communication)
      end

      it "re-renders the 'edit' template" do
        tech_communication = TechCommunication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TechCommunication.any_instance.stub(:save).and_return(false)
        put :update, :id => tech_communication.id, :tech_communication => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tech_communication" do
      tech_communication = TechCommunication.create! valid_attributes
      expect {
        delete :destroy, :id => tech_communication.id
      }.to change(TechCommunication, :count).by(-1)
    end

    it "redirects to the tech_communications list" do
      tech_communication = TechCommunication.create! valid_attributes
      delete :destroy, :id => tech_communication.id
      response.should redirect_to(tech_communications_url)
    end
  end

end
