require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VrvProjectsController do

  # This should return the minimal set of attributes required to create a valid
  # VrvProject. As you add validations to VrvProject, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all vrv_projects as @vrv_projects" do
      vrv_project = VrvProject.create! valid_attributes
      get :index
      assigns(:vrv_projects).should eq([vrv_project])
    end
  end

  describe "GET show" do
    it "assigns the requested vrv_project as @vrv_project" do
      vrv_project = VrvProject.create! valid_attributes
      get :show, :id => vrv_project.id
      assigns(:vrv_project).should eq(vrv_project)
    end
  end

  describe "GET new" do
    it "assigns a new vrv_project as @vrv_project" do
      get :new
      assigns(:vrv_project).should be_a_new(VrvProject)
    end
  end

  describe "GET edit" do
    it "assigns the requested vrv_project as @vrv_project" do
      vrv_project = VrvProject.create! valid_attributes
      get :edit, :id => vrv_project.id
      assigns(:vrv_project).should eq(vrv_project)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VrvProject" do
        expect {
          post :create, :vrv_project => valid_attributes
        }.to change(VrvProject, :count).by(1)
      end

      it "assigns a newly created vrv_project as @vrv_project" do
        post :create, :vrv_project => valid_attributes
        assigns(:vrv_project).should be_a(VrvProject)
        assigns(:vrv_project).should be_persisted
      end

      it "redirects to the created vrv_project" do
        post :create, :vrv_project => valid_attributes
        response.should redirect_to(VrvProject.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vrv_project as @vrv_project" do
        # Trigger the behavior that occurs when invalid params are submitted
        VrvProject.any_instance.stub(:save).and_return(false)
        post :create, :vrv_project => {}
        assigns(:vrv_project).should be_a_new(VrvProject)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VrvProject.any_instance.stub(:save).and_return(false)
        post :create, :vrv_project => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vrv_project" do
        vrv_project = VrvProject.create! valid_attributes
        # Assuming there are no other vrv_projects in the database, this
        # specifies that the VrvProject created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VrvProject.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => vrv_project.id, :vrv_project => {'these' => 'params'}
      end

      it "assigns the requested vrv_project as @vrv_project" do
        vrv_project = VrvProject.create! valid_attributes
        put :update, :id => vrv_project.id, :vrv_project => valid_attributes
        assigns(:vrv_project).should eq(vrv_project)
      end

      it "redirects to the vrv_project" do
        vrv_project = VrvProject.create! valid_attributes
        put :update, :id => vrv_project.id, :vrv_project => valid_attributes
        response.should redirect_to(vrv_project)
      end
    end

    describe "with invalid params" do
      it "assigns the vrv_project as @vrv_project" do
        vrv_project = VrvProject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VrvProject.any_instance.stub(:save).and_return(false)
        put :update, :id => vrv_project.id, :vrv_project => {}
        assigns(:vrv_project).should eq(vrv_project)
      end

      it "re-renders the 'edit' template" do
        vrv_project = VrvProject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VrvProject.any_instance.stub(:save).and_return(false)
        put :update, :id => vrv_project.id, :vrv_project => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vrv_project" do
      vrv_project = VrvProject.create! valid_attributes
      expect {
        delete :destroy, :id => vrv_project.id
      }.to change(VrvProject, :count).by(-1)
    end

    it "redirects to the vrv_projects list" do
      vrv_project = VrvProject.create! valid_attributes
      delete :destroy, :id => vrv_project.id
      response.should redirect_to(vrv_projects_url)
    end
  end

end
